name: pyreleaser
on:
  push:
    tags:
      - '*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
      - name: "fetch unshallow"
        run: git fetch --prune --unshallow
      - name: "list"
        run: pwd && ls -la
      - name: "deps"
        run: python -m pip install -r requirements.txt
      - name: "package"
        run: python -m build .
      - name: "list"
        run: ls -la ./dist/
      - name: "release"
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "dist/*"
